image: barichello/godot-ci:3.3.3

stages:
  - export
  - deploy

variables:
  EXPORT_NAME: not-so-lonely

linux:
  stage: export
  script:
    - mkdir -v -p build/linux
    - godot -v --export "Linux/X11" ./build/linux/$EXPORT_NAME.x86_64
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/linux
  only:
    - release

windows:
  stage: export
  script:
    - mkdir -v -p build/windows
    - godot -v --export "Windows Desktop" ./build/windows/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/windows
  only:
    - release

mac:
  stage: export
  script:
    - mkdir -v -p build/mac
    - godot -v --export "Mac OSX" ./build/mac/$EXPORT_NAME.zip
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/mac
  only:
    - release

web:
  stage: export
  script:
    - mkdir -v -p build/web
    - godot -v --export "HTML5" ./build/web/index.html
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/web
  only:
    - release

# Itch.io Deploy
itchio:linux:
  stage: deploy
  script:
    - butler push ./build/linux $ITCHIO_USERNAME/$ITCHIO_GAME:linux
  dependencies:
    - linux
  only:
    - release


itchio:web:
  stage: deploy
  script:
    - butler push ./build/web $ITCHIO_USERNAME/$ITCHIO_GAME:web
  dependencies:
    - web
  only:
    - release

itchio:windows:
  stage: deploy
  script:
    - butler login
    - butler push ./build/windows $ITCHIO_USERNAME/$ITCHIO_GAME:windows
  dependencies:
    - windows
  only:
    - release


itchio:macosx:
  stage: deploy
  script:
    - butler push ./build/mac $ITCHIO_USERNAME/$ITCHIO_GAME:mac
  dependencies:
    - mac
  only:
    - release



